### ISSUE TITLE
Display Issue

### ISSUE THREAD

**Issue by tonydero** [Daguhh/naivecalendar#2]
I'm not sure why this is happening as I can't find any errors being thrown, but whenever I run `naivecalendar.sh` the popup looks as in the image below.

I'm using `rofi 1.7.0` and I've tried `python 3.6.15`, `3.7.11`, and `3.9.6`. I'm running it directly via the cloned repo. It also happens on every theme I try.

Anywhere I can look to try to debug why it's not displaying properly?

![2021-11-16_naivecalendar](https://user-images.githubusercontent.com/29717593/142077732-77d9a6f8-953b-4d22-bf1d-d6cdae094e2f.png)

**Comment by Daguhh** [comment]
Hi, I think it's a rofi issue. 
As I can see on the [rofi discussions page](https://github.com/davatorium/rofi/discussions), the 1.7 rofi version introduce breaking changes in theme configuration.

I'm on debian, and the rofi version here is quite old (1.5.4) and if I remember well, i've tested 1.6 version, but never the 1.7.
I was able to reproduce this on a fresh manjaro intall (rofi 1.7.0-1)

I absolutely don't know if this implies a lot of change in themes, I will dig onto this and try to update them.

Thanks for raising the issue.

**Comment by Daguhh** [comment]
ok, a [small fix](https://github.com/davatorium/rofi/issues/1397) (adding 4 lines in theme config) seems to solve this issue.

I put changes on a new branch

```
git pull
git switch fix_rofi_1_7_theme_compat 
```

**Comment by tonydero** [comment]
Awesome -- thanks! Looks much better now.

And thanks in general for creating and sharing these.

**Comment by Daguhh** [comment]
Great!
Happy you like it and thanks for the feedback.
