### ISSUE TITLE
syntax error on naivecalendar.py

### ISSUE THREAD

**Issue by souravdas142** [Daguhh/naivecalendar#4]
please get it fix for, sorry no time for a MR

https://github.com/Daguhh/naivecalendar/blob/37f2ca468bc05fb41b130e0992d7affcc9dc9fd7/src/naivecalendar.py#L791

```python
# get lines with [section]
head = list(re.findall(r'\[.*\].*', note_txt))
```

**Comment by Daguhh** [comment]
fixed https://github.com/Daguhh/naivecalendar/commit/e97957377b51ae54dd95d7825d7c81e36a67c3a2
thanks
